# Vectors and Matrices

## Vectors

- [ 1.1 - Sum of Vectors](#1.1)
- [ 1.2 - Difference of Vectors](#1.2)
- [ 1.3 - Scalar Multiplication](#1.3)
- [ 1.4 - Norm of a Vector](#1.4)
- [ 1.5 - Dot Product](#1.5)

In [2]:
import numpy as np

<a name='1.1'></a>
### 1.1 - Sum of Vectors

Sum of Vectors (Vector Addition) is performed by adding the corresponding components of vectors.

Sum vector along with its individual vectors can form a parallelogram, Helps in understanding how vectors combine in space

In [3]:
# consider vector v as 1i^ + 3j^ and vector w as 4i^ - 1j^
v = np.array([
    [1],
    [3]
])
w = np.array([
    [4],
    [-1]
])

sum = v+w
print(sum)

[[5]
 [2]]


<a name='1.2'></a>
### 1.2 - Difference of Vectors

Difference of Vectors (Vector Subtraction) is performed by subtracting corresponding components of Vectors.

Difference of vectors gives idea about how far the vectors are

In [4]:
v = np.array([
    [1],
    [3]
])
w = np.array([
    [4],
    [-1]
])

diff = v-w
print(diff)

[[-3]
 [ 4]]


<a name='1.3'></a>
### 1.3 - Scalar Multiplication

Refers multiplying vector by a scalar, each element in vector gets multiplied by scalar.

By multiplying by a scalar, we are stretching the vector by a factor of scalar

In [5]:
v = np.array([
    [1],
    [2]
])
scalar = 2
smul = scalar * v
print(smul)

[[2]
 [4]]


<a name='1.4'></a>
### 1.4 - Norm of a Vector

Norm of a vector is measure of its length of magnitude.

By default np.linalg.norm() gives L2 norm.


In [6]:
v = np.array([
    [1],
    [2]
])
norm = np.linalg.norm(v)
print(norm)

2.23606797749979


<a name='1.5'></a>
### 1.5 - Dot Product

Dot product measures the similarity between two vectors. Higher the dot product more similar the vectors are, which indicates more alignment

In [8]:
x = [1,-2,-5]
y = [4,3,-1]

dot_prdt = np.dot(x,y)
print(dot_prdt)

3


In [9]:
x = np.array(x)
y = np.array(y)

dot_prdt = x@y
print(dot_prdt)

3


## Matrices

- [ 2.1 - Matrix Multiplication](#2.1)

<a name='2.1'></a>

### Matrix Multiplication

Matrix Product can be seen as multiplying two matrices or can see it as combining two linear transformations into a third linear transformation.

In [10]:
A = np.array([
    [4,9,9],
    [9,1,6],
    [9,2,3]
])
B = np.array([
    [2,2],
    [5,7],
    [4,4]
])
prdt = np.matmul(A,B)
print(prdt)

[[ 89 107]
 [ 47  49]
 [ 40  44]]


In [11]:
prdt = A@B
print(prdt)

[[ 89 107]
 [ 47  49]
 [ 40  44]]
